# development:
#   adapter: mysql2
#   host: 127.0.0.1
#   database: uuidify_dev
#   username: root
#   pool: 5
#   timeout: 5000

# test:
#   adapter: mysql2
#   host: 127.0.0.1
#   database: uuidify_test
#   username: root
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  host: 127.0.0.1
  database: uuidify_dev
  username: postgres
  password: 0R3EhgbYBBJE4KMK
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: 127.0.0.1
  database: uuidify_test
  username: postgres
  password: 0R3EhgbYBBJE4KMK
  pool: 5
  timeout: 5000

